import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class DataService {

  readonly destinations = [
    // ── North ──────────────────────────────────────────────
    { id: 'tunis', name: 'Tunis', region: 'North', shortDesc: 'A vibrant capital blending ancient medina with modern boulevards.', description: 'Tunis, the cosmopolitan capital of Tunisia, is a city where centuries of history converge with contemporary Arab culture. The ancient medina, a UNESCO World Heritage Site, winds through labyrinthine streets filled with artisan workshops, fragrant souks, and centuries-old mosques. Beyond the medina walls, the French-era Avenue Habib Bourguiba offers European-style cafés and elegant architecture.', highlights: ['Medina of Tunis (UNESCO)', 'Bardo National Museum', 'Avenue Habib Bourguiba', 'Zitouna Mosque', 'Souks & Artisan Markets'], activities: ['City Walking Tours', 'Museum Visits', 'Culinary Tours', 'Shopping', 'Nightlife'], bestSeason: 'March–May, Sep–Nov', rating: 4.7, coverImage: 'assets/images/tunis.jpg', tags: ['city', 'culture', 'history', 'medina'] },
    { id: 'sidi-bou-said', name: 'Sidi Bou Said', region: 'North', shortDesc: 'The iconic blue-and-white village perched above the Mediterranean.', description: 'Sidi Bou Said is perhaps Tunisia\'s most photographed destination, a dreamlike village of whitewashed walls and vivid cobalt-blue doors cascading down a cliff above the Gulf of Tunis. Once a haven for artists and intellectuals including Paul Klee and Gustave Flaubert, it retains an otherworldly tranquility. Jasmine-scented lanes lead to panoramic terraces overlooking the sparkling sea.', highlights: ['Blue & White Architecture', 'Café des Nattes', 'Ennejma Ezzahra Palace', 'Sea Panoramas', 'Artisan Galleries'], activities: ['Photography', 'Café Hopping', 'Art Galleries', 'Coastal Walks', 'Sunset Viewing'], bestSeason: 'Year-round, best Apr–Jun & Sep–Oct', rating: 4.9, coverImage: 'assets/images/Sidi%20Bou%20Said.jpg', tags: ['iconic', 'photography', 'coastal', 'art'] },
    { id: 'carthage', name: 'Carthage', region: 'North', shortDesc: 'Walk through the ruins of one of the ancient world\'s greatest empires.', description: 'Carthage was once the center of a Mediterranean empire that rivalled Rome itself. Today its ruins, spread across a luxurious suburb of Tunis, are a UNESCO World Heritage Site of extraordinary historical resonance. The Punic ports, Antonine Baths, Tophet sanctuary, and the sweeping views from the Byrsa Hill make this one of North Africa\'s most compelling archaeological sites.', highlights: ['Antonine Baths', 'Punic Ports', 'Tophet Sanctuary', 'Byrsa Hill', 'Carthage Museum'], activities: ['Archaeological Tours', 'History Walks', 'Museum Visits', 'Photography'], bestSeason: 'Sep–May', rating: 4.6, coverImage: 'assets/images/carthage.jpg', tags: ['ruins', 'history', 'UNESCO', 'archaeology'] },
    { id: 'bizerte', name: 'Bizerte', region: 'North', shortDesc: 'Tunisia\'s northernmost city with a charming old port and azure lagoon.', description: 'Bizerte, Africa\'s northernmost city, surprises visitors with its authentic charm. An ancient medina overlooks a picturesque old port filled with fishing boats, while the magnificent lake and canal create a unique Mediterranean landscape. Nearby, Cap Blanc marks the northernmost point of Africa, and pristine beaches stretch for miles.', highlights: ['Old Port & Kasbah', 'Bizerte Lake', 'Cap Blanc', 'Remel Beach', 'Ochre Fort'], activities: ['Sailing', 'Beach Holidays', 'Fishing Villages', 'Historical Walks'], bestSeason: 'May–Sep', rating: 4.3, coverImage: 'assets/images/bizerte.jpg', tags: ['port', 'beach', 'nature', 'authentic'] },
    { id: 'tabarka', name: 'Tabarka', region: 'North', shortDesc: 'A coral-diving paradise nestled between the sea and forested mountains.', description: 'Tabarka is where the Mediterranean meets the green mountains of the Kroumirie range. Famous for its coral reefs, exceptional diving, and the historic Genoese fort rising from an islet in the bay, Tabarka has grown into a beloved eco-tourism destination. Its jazz festival draws musicians from across the world each summer.', highlights: ['Genoese Fort', 'Coral Reefs Diving', 'Les Aiguilles Rock Formation', 'Tabarka Jazz Festival', 'Ain Draham Forest'], activities: ['Scuba Diving', 'Snorkeling', 'Hiking', 'Music Festivals', 'Eco-Tourism'], bestSeason: 'Apr–Oct', rating: 4.5, coverImage: 'assets/images/tabarka.jpg', tags: ['diving', 'nature', 'festivals', 'coastal'] },

    // ── Sahel ──────────────────────────────────────────────
    { id: 'sousse', name: 'Sousse', region: 'Sahel', shortDesc: 'The Pearl of the Sahel, where a UNESCO medina meets beautiful beaches.', description: 'Sousse is one of Tunisia\'s most beloved coastal cities, balancing a magnificent UNESCO-listed medina and ribat fortress with long sandy beaches and vibrant resort life. The city\'s strategic location on the Gulf of Hammamet has made it a crossroads of civilizations for more than three millennia. Today it offers the full range of Tunisian experiences in one compact, beautiful destination.', highlights: ['Medina of Sousse (UNESCO)', 'Ribat Fortress', 'Great Mosque of Sousse', 'Archaeological Museum', 'Boujaffar Beach'], activities: ['Beach Holidays', 'Historical Tours', 'Water Sports', 'Shopping', 'Nightlife'], bestSeason: 'Apr–Oct', rating: 4.6, coverImage: 'assets/images/Sousse.jpg', tags: ['beach', 'medina', 'UNESCO', 'resort'] },
    { id: 'monastir', name: 'Monastir', region: 'Sahel', shortDesc: 'A city of ribats, mausoleums, and the birthplace of a republic.', description: 'Monastir occupies a magnificent promontory on the Sahel coast, dominated by the great Ribat of Harthema, one of the finest Islamic fortresses in the Maghreb. Birthplace of Habib Bourguiba, Tunisia\'s first president, Monastir blends presidential heritage with pearl-white beaches and an extraordinary concentration of Islamic monuments.', highlights: ['Ribat of Monastir', 'Bourguiba Mausoleum', 'Great Mosque', 'Medina', 'Pearl White Beaches'], activities: ['Historical Tours', 'Beach Relaxation', 'Museum Visits', 'Photography'], bestSeason: 'May–Oct', rating: 4.4, coverImage: 'assets/images/monastir.jpg', tags: ['history', 'beach', 'Islamic heritage', 'authentic'] },
    { id: 'mahdia', name: 'Mahdia', region: 'Sahel', shortDesc: 'The hidden gem of the Sahel, authentic, serene, and unspoiled.', description: 'Mahdia\'s old city occupies a dramatic rocky headland jutting into the Mediterranean. Founded by the Fatimid dynasty in 912 CE as their first capital, Mahdia retains an exceptional authenticity. Its narrow medina streets, the monumental Skifa el Kahla gate, pristine beaches, and famous textile industry make it one of Tunisia\'s most rewarding off-the-beaten-path destinations.', highlights: ['Skifa el Kahla Gate', 'Fatimid Medina', 'Cap Africa Beach', 'Mahdia Port', 'Silk Weaving Workshops'], activities: ['Beach', 'Historical Walks', 'Textile Shopping', 'Seafood Dining', 'Diving'], bestSeason: 'Jun–Sep', rating: 4.5, coverImage: 'assets/images/mahdia.jpg', tags: ['authentic', 'beach', 'Fatimid', 'hidden gem'] },

    // ── Cap Bon ────────────────────────────────────────────
    { id: 'hammamet', name: 'Hammamet', region: 'Cap Bon', shortDesc: 'Tunisia\'s most beloved resort town with jasmine-scented gardens.', description: 'Hammamet is synonymous with Tunisian tourism. Blessed with sweeping white-sand beaches, a beautifully preserved medina, and lush gardens planted with citrus and jasmine, it has been welcoming international visitors since the early 20th century. André Gide, Paul Klee and countless artists discovered its charm, and today it remains Tunisia\'s premier family resort destination.', highlights: ['Old Medina & Kasbah', 'Yasmine Hammamet Marina', 'Dar Sébastien', 'Cap Bon Beaches', 'Hammamet Festival'], activities: ['Beach Holidays', 'Water Parks', 'Golf', 'Cultural Festivals', 'Watersports'], bestSeason: 'May–Sep', rating: 4.7, coverImage: 'assets/images/hammamet.jpeg', tags: ['resort', 'beach', 'family', 'gardens'] },
    { id: 'nabeul', name: 'Nabeul', region: 'Cap Bon', shortDesc: 'The pottery capital of Tunisia, fragrant with rose and jasmine.', description: 'Nabeul is the undisputed pottery capital of Tunisia, its souks overflowing with hand-painted ceramics, fragrant rose water, and woven textiles. Sitting on a beautiful stretch of Cap Bon coast, Nabeul also offers excellent beaches and serves as the gateway to exploring the lush Cap Bon peninsula, Tunisia\'s most fertile region.', highlights: ['Pottery Souks', 'Rose & Jasmine Production', 'Archaeological Museum', 'Maamoura Beach', 'Cap Bon Peninsula'], activities: ['Pottery Workshops', 'Artisan Shopping', 'Beach', 'Culinary Tours', 'Day Trips'], bestSeason: 'Year-round', rating: 4.2, coverImage: 'assets/images/nabeul.jpg', tags: ['crafts', 'pottery', 'beach', 'markets'] },

    // ── South ──────────────────────────────────────────────
    { id: 'tozeur', name: 'Tozeur', region: 'South', shortDesc: 'The gateway to the Sahara, city of palm groves and Star Wars sets.', description: 'Tozeur is the crown jewel of southern Tunisia, an oasis city of extraordinary beauty where 200,000 palm trees create a cool green haven on the edge of the Sahara. Its unique yellow-brick architecture, mysterious old quarter of Ouled El Hadef, and proximity to the Grand Erg Oriental make it the ultimate base for Sahara adventures. George Lucas immortalized the landscape as the fictional planet Tatooine.', highlights: ['Palm Grove Oasis', 'Old Quarter Ouled El Hadef', 'Chott El Jerid Salt Lake', 'Star Wars Filming Locations', 'Tozeur Zoo & Park'], activities: ['Sahara Excursions', 'Camel Trekking', 'Quad Biking', 'Star Wars Tours', 'Oasis Walks'], bestSeason: 'Oct–Apr', rating: 4.8, coverImage: 'assets/images/tozeur.jpg', tags: ['sahara', 'oasis', 'desert', 'star wars'] },
    { id: 'douz', name: 'Douz', region: 'South', shortDesc: 'The Gateway to the Sahara, where the great desert begins.', description: 'Douz proudly calls itself the Gateway to the Sahara, and rightly so. The vast golden dunes of the Grand Erg Oriental begin at its outskirts, and the town serves as the main departure point for camel treks and 4x4 expeditions into the Saharan wilderness. The annual International Festival of the Sahara celebrates Bedouin culture with camel races, music, and traditional art.', highlights: ['Grand Erg Oriental Dunes', 'Camel Trek Departures', 'Festival of the Sahara', 'Desert Palm Groves', 'Bedouin Culture'], activities: ['Camel Trekking', 'Quad Adventures', '4x4 Desert Safari', 'Star Gazing', 'Bedouin Camp Experiences'], bestSeason: 'Oct–Mar', rating: 4.7, coverImage: 'assets/images/douz.jpg', tags: ['sahara', 'dunes', 'camel', 'desert'] },
    { id: 'tataouine', name: 'Tataouine', region: 'South', shortDesc: 'Ancient Berber ksar villages carved into desert mountains.', description: 'The name Tataouine became globally famous as the inspiration for Star Wars\' Tatooine. But long before cinema, this region\'s extraordinary ksar (fortified granary villages) had been drawing wonder from travelers. Perched dramatically on cliffsides and mountain ridges, these ancient Berber structures, including Ksar Ouled Soltane, Ksar Hadada and Ksar Ezahra, are among the most distinctive architectural achievements in North Africa.', highlights: ['Ksar Ouled Soltane', 'Ksar Hadada', 'Chenini Berber Village', 'Ghomrassen', 'Star Wars Locations'], activities: ['Ksar Village Tours', 'Berber Culture', 'Star Wars Tourism', '4x4 Adventures', 'Photography'], bestSeason: 'Oct–Apr', rating: 4.6, coverImage: 'assets/images/tataouine.jpg', tags: ['berber', 'ksar', 'star wars', 'desert'] },
    { id: 'matmata', name: 'Matmata', region: 'South', shortDesc: 'An underground Berber world built into the earth itself.', description: 'Matmata\'s troglodyte dwellings are among the most remarkable habitations on Earth. For centuries the Berber Matmata people carved their homes into the soft rock, creating underground courtyards and living chambers that provide natural insulation against the extreme desert heat. George Lucas filmed here for the Mos Eisley scenes in Star Wars, and some families still live in these extraordinary underground homes.', highlights: ['Troglodyte Houses', 'Star Wars Hotel Sidi Driss', 'Berber Underground Life', 'Doiret Village', 'Pottery Crafts'], activities: ['Underground House Tours', 'Cultural Visits', 'Photography', 'Berber Cuisine', 'Desert Walks'], bestSeason: 'Oct–Apr', rating: 4.5, coverImage: 'assets/images/matmata.jpg', tags: ['troglodyte', 'berber', 'underground', 'star wars'] },

    // ── Island ─────────────────────────────────────────────
    { id: 'djerba', name: 'Djerba', region: 'Island', shortDesc: 'The Island of Dreams, rich in ancient culture, beaches, and tranquility.', description: 'Djerba, the legendary island of the Lotus Eaters from Homer\'s Odyssey, is Tunisia\'s most beloved island destination. Connected to the mainland by a Roman causeway, Djerba offers a unique blend of Arab, Berber, Jewish, and Mediterranean cultures. Its whitewashed architecture, ancient synagogue, traditional pottery villages, and spectacular beaches create an experience unlike anywhere else in North Africa.', highlights: ['Houmt Souk Medina', 'El Ghriba Synagogue', 'Guellala Pottery Village', 'Aghir Beach', 'Djerbahood Murals'], activities: ['Beach Holidays', 'Cultural Tours', 'Water Sports', 'Jewish Heritage', 'Camel Riding', 'Pottery Workshops'], bestSeason: 'Apr–Oct', rating: 4.8, coverImage: 'assets/images/djerba.jpg', tags: ['island', 'beach', 'culture', 'UNESCO', 'multicultural'] },
  ];

  readonly tours = [
    { id: 't1', name: '3 Days in Tunis', slug: '3-days-tunis', shortDesc: 'Immerse yourself in the ancient medina and modern boulevards of the capital.', description: 'Three unforgettable days exploring Tunisia\'s cosmopolitan capital, from the winding lanes of the UNESCO medina to the magnificent ruins of Carthage and the iconic blue village of Sidi Bou Said.', price: 450, duration: 3, category: 'City', difficulty: 'Easy', coverImage: 'assets/images/tunis.jpg', includes: ['2 Nights Hotel', 'Breakfast Daily', 'Expert Guide', 'Airport Transfers', 'Entry Fees'], excludes: ['Flights', 'Lunch & Dinner', 'Personal Expenses'], rating: 4.8, reviewsCount: 124, featured: true, itinerary: [ { day: 1, title: 'Arrival & Medina Discovery', description: 'Arrive in Tunis, check in to your hotel, then explore the UNESCO-listed medina with its grand mosques, artisan souks and centuries-old architecture. Evening dinner at a traditional riad.' }, { day: 2, title: 'Carthage & Sidi Bou Said', description: 'Morning tour of the extraordinary ruins of ancient Carthage, then lunch with panoramic sea views. Afternoon in the iconic blue-and-white village of Sidi Bou Said.' }, { day: 3, title: 'Bardo Museum & Departure', description: 'Visit the world-famous Bardo National Museum, home to the finest Roman mosaic collection in existence, before transfer to the airport.' } ] },
    { id: 't2', name: 'Sahara Adventure', slug: 'sahara-adventure', shortDesc: 'Dunes, camels, and a billion stars. The Sahara as it should be.', description: 'Five days in Tunisia\'s magnificent south: the oasis city of Tozeur, the shifting dunes of the Grand Erg Oriental, camel trekking at sunset, and a night under the Saharan stars.', price: 890, duration: 5, category: 'Adventure', difficulty: 'Moderate', coverImage: 'assets/images/kairouan.jpg', includes: ['4 Nights Accommodation', 'Breakfast & Dinner', 'Expert Desert Guide', 'Camel Trek', 'Desert Camp Night', '4x4 Transport', 'All Entries'], excludes: ['Flights to Tozeur', 'Lunch', 'Travel Insurance'], rating: 4.9, reviewsCount: 89, featured: true, itinerary: [ { day: 1, title: 'Arrive Tozeur – Palm Oasis', description: 'Arrive at Tozeur airport. Explore the extraordinary palm oasis (200,000 trees) and the ancient brick quarter of Ouled El Hadef. Overnight in a traditional maison d\'hôtes.' }, { day: 2, title: 'Chott El Jerid & Douz', description: 'Cross the otherworldly Chott El Jerid salt lake. Arrive in Douz, Gateway to the Sahara. Camel ride at sunset into the first dunes.' }, { day: 3, title: 'Deep Desert Safari', description: 'Full-day 4x4 expedition into the Grand Erg Oriental. Lunch at a desert oasis. Overnight in a traditional Bedouin camp under a canopy of stars.' }, { day: 4, title: 'Ksar Villages & Matmata', description: 'Visit the ancient Berber ksar villages of Ksar Ghilane, then drive to Matmata to see the extraordinary troglodyte underground dwellings.' }, { day: 5, title: 'Return Tozeur & Departure', description: 'Morning at leisure in Tozeur souk. Transfer to airport for departure.' } ] },
    { id: 't3', name: 'Coastal Discovery', slug: 'coastal-discovery', shortDesc: 'Mediterranean gold, from Hammamet to Djerba along the Tunisian coast.', description: 'Seven days exploring Tunisia\'s most beautiful coastline: pristine beaches, ancient medinas, coral diving in Tabarka, and the legendary island of Djerba.', price: 1290, duration: 7, category: 'Beach', difficulty: 'Easy', coverImage: 'assets/images/hammamet.jpeg', includes: ['6 Nights Hotels', 'Breakfast Daily', 'Transport', 'Guide (Historical Sites)', 'Ferry to Djerba'], excludes: ['Flights', 'Lunches & Dinners', 'Optional Activities'], rating: 4.7, reviewsCount: 67, featured: true, itinerary: [ { day: 1, title: 'Hammamet Arrival', description: 'Arrive and settle into your beachfront hotel. Afternoon visit to Hammamet\'s picturesque medina.' }, { day: 2, title: 'Cap Bon Explorer', description: 'Drive through the lush Cap Bon peninsula: Nabeul pottery market, Kelibia fortress, vineyards.' }, { day: 3, title: 'Sousse & Monastir', description: 'Sousse UNESCO medina and ribat fortress. Afternoon in Monastir.' }, { day: 4, title: 'Mahdia – Hidden Gem', description: 'Drive to authentic Mahdia. Explore the Fatimid medina and beautiful beaches.' }, { day: 5, title: 'Sfax & Journey South', description: 'Visit Tunisia\'s second city, the medina of Sfax. Continue south.' }, { day: 6, title: 'Djerba Island', description: 'Ferry to Djerba. Explore Houmt Souk, El Ghriba Synagogue, and beaches.' }, { day: 7, title: 'Djerba – Departure', description: 'Final morning on the beach. Transfer to airport.' } ] },
    { id: 't4', name: 'Tunisia Grand Tour', slug: 'tunisia-grand-tour', shortDesc: 'The definitive Tunisia experience, from north to south in 10 days.', description: 'The complete Tunisia: Tunis and Carthage, Cap Bon, Sahel coast, ancient Kairouan, Saharan south, Berber villages, and the island of Djerba. Tunisia at its absolute finest.', price: 2200, duration: 10, category: 'Cultural', difficulty: 'Moderate', coverImage: 'assets/images/carthage.jpg', includes: ['9 Nights Hotels', 'Breakfast & Dinner Daily', 'Private Guide', 'All Transfers', 'Entry Fees', 'Desert Camp', 'Camel Trek'], excludes: ['International Flights', 'Lunches', 'Travel Insurance', 'Personal Expenses'], rating: 4.9, reviewsCount: 45, featured: true, itinerary: [ { day: 1, title: 'Arrival Tunis', description: 'Welcome to Tunisia. Transfer to Tunis hotel. Evening medina walk.' }, { day: 2, title: 'Tunis & Carthage', description: 'Bardo Museum, Carthage ruins, Sidi Bou Said.' }, { day: 3, title: 'Cap Bon', description: 'Hammamet, Nabeul, Kelibia.' }, { day: 4, title: 'Sahel Coast', description: 'Sousse medina and ribat, Monastir, Mahdia.' }, { day: 5, title: 'Kairouan', description: 'UNESCO holy city of Kairouan, Great Mosque, medina.' }, { day: 6, title: 'El Djem & South Journey', description: 'Magnificent Roman amphitheatre of El Djem, drive south.' }, { day: 7, title: 'Tozeur & Oasis', description: 'Tozeur palm oasis, Chott El Jerid.' }, { day: 8, title: 'Desert Sahara', description: 'Deep desert 4x4 safari, Bedouin camp overnight.' }, { day: 9, title: 'Berber Villages & Djerba', description: 'Matmata, Tataouine ksars, arrival Djerba.' }, { day: 10, title: 'Djerba Departure', description: 'Morning exploration, departure.' } ] },
    { id: 't5', name: 'Luxury Tunisia Escape', slug: 'luxury-escape', shortDesc: 'Five-star comforts, private guides, and exclusive Tunisian experiences.', description: 'Tunisia through a luxury lens: boutique riads in Sidi Bou Said, private yacht excursions, helicopter views of the Sahara, and exclusive access to private archaeological sites with expert historians.', price: 4500, duration: 8, category: 'Luxury', difficulty: 'Easy', coverImage: 'assets/images/Sidi%20Bou%20Said.jpg', includes: ['7 Nights 5-Star Hotels & Boutique Riads', 'All Meals (Curated)', 'Private Guide', 'Private Transport', 'Helicopter Tour', 'Private Yacht Half-Day', 'Exclusive Archaeological Access', 'Spa Credit'], excludes: ['International Flights', 'Travel Insurance', 'Personal Shopping'], rating: 5.0, reviewsCount: 18, featured: true, itinerary: [ { day: 1, title: 'Arrival Tunis – Boutique Riad', description: 'Private airport transfer. Check in to exclusive medina riad. Private sunset cocktails on the terrace.' }, { day: 2, title: 'Private Carthage & Bardo VIP', description: 'Exclusive private Carthage tour with lead archaeologist. VIP Bardo Museum after-hours access.' }, { day: 3, title: 'Cap Bon Yacht Day', description: 'Private yacht from Hammamet along the Cap Bon coastline. Gourmet lunch on board.' }, { day: 4, title: 'Sahel & Kairouan', description: 'Private Sousse medina tour. Exclusive Kairouan access before public opening.' }, { day: 5, title: 'Fly to Tozeur', description: 'Private flight to Tozeur. Luxury desert lodge check-in.' }, { day: 6, title: 'Helicopter Sahara Tour', description: 'Exclusive helicopter tour over the Erg Oriental dunes. Private camel sunset trek.' }, { day: 7, title: 'Djerba by Private Plane', description: 'Fly to Djerba. Exclusive El Ghriba access. Luxury beachfront villa.' }, { day: 8, title: 'Final Day & Departure', description: 'Spa morning. Private departure.' } ] }
  ];

  readonly blogPosts = [
    { id: 'b1', title: 'Best Beaches in Tunisia: A Complete Guide', slug: 'best-beaches-tunisia', category: 'Beaches', excerpt: 'From the crystal waters of Kelibia to the golden sands of Djerba, we reveal Tunisia\'s most spectacular beaches for every type of traveler.', readTime: 8, coverImage: 'assets/images/hammamet.jpeg', createdAt: '2024-05-15', authorName: 'Sarah Mahmoud', featured: true },
    { id: 'b2', title: 'The Ultimate Sahara Desert Guide', slug: 'ultimate-sahara-guide', category: 'Desert', excerpt: 'Everything you need to know for your first Saharan adventure: choosing the right tour, what to pack for nights under the stars.', readTime: 12, coverImage: 'assets/images/kairouan.jpg', createdAt: '2024-04-22', authorName: 'Ahmed Ben Salem', featured: true },
    { id: 'b3', title: 'Sidi Bou Said: A Day in the Blue Village', slug: 'visiting-sidi-bou-said', category: 'Culture', excerpt: 'Our photographer\'s guide to the most beautiful morning walk in Tunisia, with jasmine, cobalt doorways, and views that stop you in your tracks.', readTime: 6, coverImage: 'assets/images/Sidi%20Bou%20Said.jpg', createdAt: '2024-04-08', authorName: 'Leila Dridi', featured: false },
    { id: 'b4', title: 'Traditional Tunisian Cuisine You Must Try', slug: 'traditional-tunisian-cuisine', category: 'Food', excerpt: 'Couscous, brik, harissa, tajine, and makroudh: a mouth-watering guide to the dishes that define Tunisian culinary identity.', readTime: 9, coverImage: 'assets/images/tunis.jpg', createdAt: '2024-03-30', authorName: 'Fatima Chakroun', featured: false },
    { id: 'b5', title: 'Hidden Gems of Tunisia: Beyond the Tourist Trail', slug: 'hidden-gems-tunisia', category: 'Tips', excerpt: 'Skip the crowds and discover the Tunisia that most visitors never see, from secret mountain villages to ancient ruins found off the map.', readTime: 11, coverImage: 'assets/images/eljem.jpg', createdAt: '2024-03-15', authorName: 'Omar Trabelsi', featured: false },
    { id: 'b6', title: 'UNESCO Sites of Tunisia: A Heritage Journey', slug: 'unesco-sites-tunisia', category: 'History', excerpt: 'Tunisia boasts eight UNESCO World Heritage Sites. Join us on a journey through millennia of civilization: Carthage, Kairouan, El Djem and beyond.', readTime: 14, coverImage: 'assets/images/carthage.jpg', createdAt: '2024-02-28', authorName: 'Nadia Hamdi', featured: false },
  ];

  readonly experiences = [
    { id: 'e1', title: 'Sahara Desert Tours', icon: 'bi-sun', gradient: 'linear-gradient(135deg, #B8860B, #DEB887)', description: 'Venture into the Grand Erg Oriental on guided 4x4 expeditions. Watch sunsets paint the dunes gold from the back of a camel.', coverImage: 'assets/images/sahara%20desert%20tours.jpg' },
    { id: 'e2', title: 'Camel Trekking', icon: 'bi-compass', gradient: 'linear-gradient(135deg, #8B6914, #D4AF37)', description: 'The quintessential Saharan experience. Trek on camelback through desert landscapes unchanged for millennia, ending at a Bedouin camp.', coverImage: 'assets/images/camel%20trekking.jpg' },
    { id: 'e3', title: 'Scuba Diving', icon: 'bi-water', gradient: 'linear-gradient(135deg, #1B6CA8, #89C4E1)', description: 'Explore coral reefs, ancient shipwrecks, and extraordinary marine life in the crystal-clear waters of Tabarka and Cap Bon.', coverImage: 'assets/images/hammamet.jpeg' },
    { id: 'e4', title: 'Historical Tours', icon: 'bi-bank', gradient: 'linear-gradient(135deg, #2C3E6B, #4A6FA5)', description: 'Walk through 3,000 years of history: Punic Carthage, Roman amphitheatres, Arab medinas, and Byzantine fortresses.', coverImage: 'assets/images/eljem.jpg' },
    { id: 'e5', title: 'Beach Holidays', icon: 'bi-umbrella', gradient: 'linear-gradient(135deg, #1B4F8A, #89C4E1)', description: 'Over 1,300km of Mediterranean and Atlantic coastline with crystalline waters, white sand, and world-class resorts.', coverImage: 'assets/images/hammamet.jpeg' },
    { id: 'e6', title: 'Food & Culinary Tours', icon: 'bi-egg-fried', gradient: 'linear-gradient(135deg, #8B4513, #D4A76A)', description: 'Discover the bold flavors of Tunisian cuisine: harissa-spiced briks, slow-cooked tagines, and fragrant couscous at family tables.', coverImage: 'assets/images/food.jpeg' },
    { id: 'e7', title: 'Photography Trips', icon: 'bi-camera', gradient: 'linear-gradient(135deg, #4A4A4A, #8B8B8B)', description: 'Tunisia offers extraordinary photographic subjects: blue doors in Sidi Bou Said, Saharan dune patterns, Roman ruins at golden hour.', coverImage: 'assets/images/Sidi%20Bou%20Said.jpg' },
    { id: 'e8', title: 'Star Gazing', icon: 'bi-stars', gradient: 'linear-gradient(135deg, #1a1a2e, #16213e)', description: 'The Saharan sky offers one of the clearest views of the cosmos on earth. Let our astronomy guides lead you through the constellations.', coverImage: 'assets/images/star%20gazing.jpg' },
    { id: 'e9', title: 'Cultural Experiences', icon: 'bi-people', gradient: 'linear-gradient(135deg, #6B2D8B, #9B59B6)', description: 'Share tea with artisans in Nabeul, attend a wedding in Djerba, visit a Jewish community, experience Berber hospitality in Matmata.', coverImage: 'assets/images/Sousse.jpg' },
    { id: 'e10', title: 'Quad Bike Adventures', icon: 'bi-lightning', gradient: 'linear-gradient(135deg, #C0392B, #E74C3C)', description: 'Rev across desert terrain on thrilling quad bike excursions through rocky gorges, salt lakes, and the dune sea of the Sahara.', coverImage: 'assets/images/quad%20bike.webp' },
  ];

  readonly testimonials = [
    { name: 'Sophie Laurent', country: 'France', rating: 5, comment: 'The Sahara Adventure tour was the most extraordinary experience of my life. Waking up to sunrise over the dunes, the silence, the infinite sky. Our guide Karim made every moment magical. Tunisia exceeded every expectation.', tourName: 'Sahara Adventure', avatar: '' },
    { name: 'James & Rachel Chen', country: 'United Kingdom', rating: 5, comment: 'TunisiaVista organized our honeymoon and we couldn\'t have asked for more. The Luxury Escape package was flawlessly executed. Sidi Bou Said, private Carthage access, Djerba villa. Pure perfection.', tourName: 'Luxury Tunisia Escape', avatar: '' },
    { name: 'Marco Rossi', country: 'Italy', rating: 5, comment: 'As a history enthusiast, the Grand Tour was everything I dreamed of. The guides\' knowledge of Carthage and Kairouan was encyclopedic. I\'ve traveled extensively, and Tunisia\'s heritage rivals anywhere in the Mediterranean.', tourName: 'Tunisia Grand Tour', avatar: '' },
    { name: 'Astrid Lindqvist', country: 'Sweden', rating: 5, comment: 'Completely fell in love with Tunisia through the Coastal Discovery tour. The beaches are stunning, the food incredible, and the people so warm. Sidi Bou Said alone was worth the journey. Will be back next year!', tourName: 'Coastal Discovery', avatar: '' },
    { name: 'Tariq Al-Rasheed', country: 'UAE', rating: 4, comment: 'The 3 Days in Tunis package gave me a perfect introduction to this incredible country. The medina, Carthage, Sidi Bou Said, all perfectly organized. Professional service and deeply knowledgeable local guides.', tourName: '3 Days in Tunis', avatar: '' },
    { name: 'Elena Volkova', country: 'Russia', rating: 5, comment: 'Matmata and the Berber villages were unlike anything I\'ve ever seen. TunisiaVista\'s local connections opened doors to experiences that no generic tour company could offer. An authentic, profound journey.', tourName: 'Tunisia Grand Tour', avatar: '' },
  ];

  getStars(rating: number): string {
    return '★'.repeat(Math.floor(rating)) + (rating % 1 >= 0.5 ? '½' : '');
  }

  getRegions(): string[] {
    return ['North', 'Sahel', 'Cap Bon', 'South', 'Island'];
  }
}
